### ISSUE TITLE
Help making text centered

### ISSUE THREAD

**Issue by jesi-rgb** [coldtype/coldtype#152]
One thing I cannot find in the docs is how to center stuff. I remember that sometime ago, stacking was centered by default and there was an argument that I cannot remember that accepted 'mdy', 'mxy', and that sort of alignment commands. 

Now that code does not work. How do you center stuff with the stack() function?

<img width="862" alt="image" src="https://github.com/coldtype/coldtype/assets/50735312/d0c973dd-e1c3-4f22-a060-206f7fe0d879">

<img width="1476" alt="image" src="https://github.com/coldtype/coldtype/assets/50735312/836ff0f1-6302-4ae6-8973-04583daf3b93">

Moreover, I'd love to know how to center multiline text setup like this:
```python
st = StSt("COLDEST\nTYPE", mono, 200, wght=1).fill(FG).align(f.a.r)
```

which renders this:

<img width="862" alt="image" src="https://github.com/coldtype/coldtype/assets/50735312/19cd9268-15fe-4e07-b64c-fab53e7e1845">

**Comment by stenson** [comment]
Ah! This should be `.xalign(r)` for both cases — used quite a bit in the examples but yeah the documentation (as always) could use use some work.

```python
from coldtype import *

@renderable((1080, 540), bg=1)
def aligns(r):
    ri = r.inset(100)
    return (P(
        P(r.inset(50)).fssw(-1, 0, 1),
        StSt("Coldest\nType".upper(), Font.MuSan(), fs:=72).xalign(ri, "W").align(ri, "NW"),
        StSt("Coldest\nType".upper(), Font.MuSan(), fs).xalign(ri).align(ri),
        StSt("Coldest\nType".upper(), Font.MuSan(), fs).xalign(ri, "E").align(ri, "SE"),
        ))
```

![linealigning_aligns](https://github.com/coldtype/coldtype/assets/89770/12cda338-bc94-4a35-8ec2-9466f776ad35)

"W"/"NW"/"SE" etc. are compass directions, west, northwest, southeast, etc.

Will add this snippet as an example to the repo as well.

**Comment by jesi-rgb** [comment]
thanks so much for the quick response!

I would love to contribute somehow to the documentation, I've figured out several things that I too believe could need an explainer to newbies (I am talking grids, among other cool features)

How could we organize ourselves? Should we jot down a list of things and start working on that? I really wanna contribute to this marvelous work!

**Comment by stenson** [comment]
cool! yeah I think jotting down a list of things sounds great — I'm a little busy for the next couple weeks but happy to talk more about it in the future
