### ISSUE TITLE
Install CT to Python 3.12: `ModuleNotFoundError: No module named 'websockets'`

### ISSUE THREAD

**Issue by Mark2Mark** [coldtype/coldtype#155]
### Disclaimer
- This only happens with Python 3.12
- I checked with 3.11 now, and there it works

---

Hi, I wanted to install a new coldtype from scratch after a while of using a rather old version for a long time. I don’t want to update that old version, as that has broken many of my scripts in the past. Instead, I wanted to make a new directory with a new version of CT and then – one by one – move my scripts to the new version, checking if all still works.

However, I get the error from the title above.

Install into a new venv from scratch:

1. check python
```sh
python3 --version
Python 3.12.0
```

2. create venv
```sh
python3.12 -m venv venv
```

3. activate venv
```sh
source venv/bin/activate
```

4. install coldtype
```sh
pip install "coldtype[viewer]"
``` 

4. Traceback for `coldtype demo` right after installing
```sh
Traceback (most recent call last):
  File "/Users/.../Coldtype/venv/bin/coldtype", line 7, in <module>
    from coldtype.renderer import main
  File "/Users/.../Coldtype/venv/lib/python3.12/site-packages/coldtype/renderer/__init__.py", line 6, in <module>
    import websockets
ModuleNotFoundError: No module named 'websockets'
```

5. double check venv
```sh
echo $VIRTUAL_ENV
/Users/.../Coldtype/venv
```

6. check installed modules
```sh
pip list -l
Package           Version
----------------- -----------
appdirs           1.4.4
booleanOperations 0.9.0
Brotli            1.1.0
cffi              1.16.0
cffsubr           0.2.9.post1
coldtype          0.0.5
defcon            0.10.3
easing-functions  1.0.4
fontPens          0.2.4
fonttools         4.46.0
freetype-py       2.4.0
fs                2.4.16
lxml              4.9.3
mido              1.3.0
numpy             1.26.2
packaging         23.2
pip               23.2.1
pyclipper         1.3.0.post5
pycparser         2.21
python-bidi       0.4.2
setuptools        69.0.2
six               1.16.0
skia-pathops      0.8.0.post1
ufo2ft            2.33.4
uharfbuzz         0.37.3
unicodedata2      15.1.0
xattr             1.0.0
zopfli            0.2.3
```

**Comment by stenson** [comment]
Sorry for the runaround here — in general I wouldn't recommend using coldtype with new .0 releases of Python, as coldtype relies on a number of c-compiled packages, which often don't get released all that soon after the .0 releases. That said, the much bigger issue here is that the maintainers of `skia-python` have decided to release only a much newer Skia version for >=3.12, which has a lot of bugs that need to be fixed (both by me and by them), so I don't think coldtype will work for a while on >= 3.12

**Comment by Mark2Mark** [comment]
Thanks for the info and no problem about the runaround :D 

I will happily use 3.11 for a while. I also thought .12 might be too new.
Sorry to hear about the hassle you encounter with Skia. I am totally fine to stick with 3.11 for Coldtype. Just good to know the whereabouts. I am currently trying to clean my setup in order to get everything up and running faster when an idea pops to mind.

Thanks so much! I think I can close the isse? Feel free to re-open if you want its ticket for later.
