### ISSUE TITLE
video player reset = same as decrease

### ISSUE THREAD

**Issue by Mark2Mark** [coldtype/coldtype#157]
https://github.com/coldtype/coldtype/blob/6b6bf53c1477231bde128ade4032b08c16f762e7/coldtype/renderer/keyboard.py#L76C5-L76C64

```
ViewerPlaybackSpeedDecrease = "viewer_playback_speed_decrease"
ViewerPlaybackSpeedReset = "viewer_playback_speed_decrease"
```

Is this on purpose? I’d think decrease is not the same as a reset.

**Comment by stenson** [comment]
`ViewerPlaybackSpeedReset` isn't actually implemented or mapped to a keyboard shortcut, but I've gone ahead and fixed that value inconsistency
