### ISSUE TITLE
Issue with Speed on different machines

### ISSUE THREAD

**Issue by schoudhary101** [coldtype/coldtype#160]
I am trying to generate mp4/PNGs for different animations via command line and python file. 
On Mac M2 Pro, it is superfast but on a cloud linux VM (with cheap CPU with 16 cores and a T4 GPU) its superslow. 
I tried playing with -tc and -mp parameters, they didnt have any effect on the rendering time.

**Comment by stenson** [comment]
yeah I've experienced the exact same thing — I wish I knew why it was happening! for some reason it's not all that slow on google colab (their notebook-hosting service) (here's an example of coldtype running there https://colab.research.google.com/drive/1IQnOZuvmNYO5k-VopgwZwl41Rqa0kE8Y), but yeah definitely not as fast as on a modern mac or even a modern pc

**Comment by schoudhary101** [comment]
Strange thing is, I ran it in a notebook on the same cloud VM. It had similar speed to mac though I didn't write it as a mp4/PNGs but used "render_show=True" parameter to show animations in the notebook. 
That may mean CLI run has discrepancies.

**Comment by schoudhary101** [comment]
This was faster through notebook.
```
from coldtype import *
import os
import glob
from coldtype.fx.skia import phototype
from moviepy.editor import VideoFileClip, CompositeVideoClip

fnt = Font.MutatorSans()

@animation(timeline=Timeline(90, 24), bg=-1, render_bg=-1)
def glyphwise(f):
    def styler(g):
        return [
            Style(fnt, 250, wdth=0.15), # metrics
            Style(fnt, 250 # animated
                , wdth=f.adj(-g.i*2).e("eeio", 2)
                , wght=f.adj(-g.i*3).e("seio", 3)
                , ro=1
                , ty=1
                )]

    # should also work w/o an \n in between COLD & TYPE
    return (Glyphwise("SERENITY", styler, multiline=1)
        .xalign(f.a.r, tx=0)
        .lead(30)
        .align(f.a.r, tx=0)
        .reverse(recursive=True)
        .fssw(1, 0, 7, 1)
        .ch(phototype(f.a.r, 3, 190, cutw=15)))

frame_path = glyphwise.render_and_rasterize()
```

**Comment by schoudhary101** [comment]
we can use render_and_rasterize
