### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by matheusmanto** [coldtype/coldtype#36]
Hi there!

I tried to install Coldtype by following all the steps in the Install page and everything went fine until the last step:
- Then pip install -e . (This adds the coldtype command to your virtual environment)
- Then coldtype
I did the last step and at the bottom there is an error message:

    import skia
ImportError: dlopen(/Users/matheusmantovani/coldtype/venv/lib/python3.9/site-packages/skia.cpython-39-darwin.so, 2): Symbol not found: _XML_ErrorString
  Referenced from: /Users/matheusmantovani/coldtype/venv/lib/python3.9/site-packages/skia.cpython-39-darwin.so
  Expected in: flat namespace
 in /Users/matheusmantovani/coldtype/venv/lib/python3.9/site-packages/skia.cpython-39-darwin.so

Do you guys know how to fix it? I'm very new at coding, so I would appreciate some help.

Thank you!

**Comment by stenson** [comment]
Hello! I can't say I've run into that error. What version of Mac OS are you using?

And what do you see when you have the virtual environment activated and you just type in `python` and hit enter in your terminal?

For reference, I see this on my setup when I do that:

```Python 3.9.0 (v3.9.0:9cf6752276, Oct  5 2020, 11:29:23) 
[Clang 6.0 (clang-600.0.57)] on darwin```

**Comment by matheusmanto** [comment]
Hi, Rob! First of all, I am your fan! And thanks a lot for the pretty fast
answer.

Mine is a MacOS Mojave Version 10.14.6

Here is what I see when I have the virtual environment activated and I just
type in *python* and hit enter in my terminal:

Python 3.9.1 (v3.9.1:1e5d33e9b9, Dec  7 2020, 12:10:52)

[Clang 6.0 (clang-600.0.57)] on darwin

I can see a little difference between our python versions. Maybe it's that?
Maybe I should try to reinstall python in a previous version?

Thanks again, Rob!

Regards from Brasil!

Matheus

Em qua., 13 de jan. de 2021 às 23:17, Rob Stenson <notifications@github.com>
escreveu:

**Comment by stenson** [comment]
Thanks for the kind words! I just tried 3.9.1 on my Catalina machine, but it doesn't have the issue you've described, so I don't think it's about the difference between our versions. I did find one thread on a similar issue (by searching Google for `Symbol not found: _XML_ErrorString`), and it looks like you might need to install Xcode and its "Command Line Tools" package — do you have Xcode installed on your machine?

You could also try installing an older version of Python, like the 3.8.7 version available here: https://www.python.org/downloads/mac-osx/ — I'm not sure that would help, but I know 3.8 is more stable than the current 3.9 releases.

**Comment by matheusmanto** [comment]
Hi, Rob! I installed the Xcode and the Command Line Tools package and then
I went to the Terminal and I did the Coldtype install steps again, but it
didn't work. Then I removed the Python 3.9 and installed the Python 3.8.7
and still the same error. I'm sorry to bother you with this problem, but
I'm really looking forward to use Coldtype!

Thanks again for your help.

Matheus

Em qui., 14 de jan. de 2021 às 13:45, Rob Stenson <notifications@github.com>
escreveu:

**Comment by stenson** [comment]
Hi Matheus — apologies again that the install is turning out to be so difficult! Unfortunately in a case like this there's not much I can do to help, since this appears to be an issue with some lower-level python libraries failing to install correctly on your machine, not an issue with Coldtype itself. Are you installing python via brew? And is there a particular reason you're on Mojave and not a newer OS?

My general approach to a problem like the one you're seeing (I've run into many similar inscrutable errors like this over the years), is to fish around on google for people experiencing similar issues, i.e. here `Symbol not found: _XML_ErrorString`. Most of what I'm seeing when I google that is that there are strange issues related to the Mac SDK that Xcode installs, potentially being incompatible, though it's hard for me to say what would help, since I can't test any of the potential fixes on my computer.

**Comment by matheusmanto** [comment]
Hi, Rob! Thanks a lot for all your help! I will try to update my mac and
I'll do some research about this error. Thank you for being so supportive
and keep up the very good work you have been doing.

Best regards from Brasil.

Matheus

Em ter, 19 de jan de 2021 15:08, Rob Stenson <notifications@github.com>
escreveu:

**Comment by benjaminwelch** [comment]
@matheusmanto I'm having this same exact issue and I'm also on Mojave. I wonder if that's related.

I've upgrade Xcode and the command line tools to the latest supported version for Mojave. This hasn't solved it.

Have you had any luck? I'll report back if I'm able to solve it. Really want to get this working but I'm also new to programming. Good luck!

**Comment by matheusmanto** [comment]
Hi, Benjamin! I updated to Big Sur and still have the same problem. Not
solved yet. If you find a way to fix it, please let me know. Thanks!

Em ter, 16 de mar de 2021 13:02, Benjamin Welch ***@***.***>
escreveu:

**Comment by benjaminwelch** [comment]
I've done some more testing but haven't found a solution yet. I was able to get things working on another computer running Catalina. I didn't ever run into this issue.

The Catalina machine has a more recent version of the command line tools which might be part of it. My Mojave machine has 11.3.1 and the Catalina machine has command line tools 11.5.

@matheusmanto Do you know which version of the command line tools you have installed? This may help: [command-line tools](https://developer.apple.com/library/archive/technotes/tn2339/_index.html#//apple_ref/doc/uid/DTS40014588-CH1-HOW_CAN_I_UNINSTALL_THE_COMMAND_LINE_TOOLS_)

If you still have 11.3, I would try updating and seeing if that gets things working.

**Comment by matheusmanto** [comment]
I'll try that! Thank you!

Em ter., 16 de mar. de 2021 às 18:56, Benjamin Welch <
***@***.***> escreveu:

**Comment by stenson** [comment]
Not sure if anyone on this thread is still interested in installing coldtype (as it's been quite a while!), but I've tested coldtype on mojave myself recently & if you run `pip install skia-python==86.1` after installing coldtype, that should fix this issue (which is that the latest versions of skia-python aren't compiled on mojave so they won't install there) — more info about installing here: https://coldtype.goodhertz.com/install.html

**Comment by benjaminwelch** [comment]
@stenson Thanks so much. That worked and I'm no longer getting the previous error. However, I now see this when I try to run `coldtype demo`:

```
(venv) benjaminwelch:coldtype: coldtype demo
Traceback (most recent call last):
  File "/Users/benjaminwelch/open-source/coldtype/venv/bin/coldtype", line 8, in <module>
    sys.exit(main())
  File "/Users/benjaminwelch/open-source/coldtype/venv/lib/python3.9/site-packages/coldtype/renderer/__init__.py", line 2337, in main
    Renderer(parser).main()
  File "/Users/benjaminwelch/open-source/coldtype/venv/lib/python3.9/site-packages/coldtype/renderer/__init__.py", line 263, in __init__
    self.source_reader = SourceReader(
  File "/Users/benjaminwelch/open-source/coldtype/venv/lib/python3.9/site-packages/coldtype/renderer/reader.py", line 254, in __init__
    self.read_configs(cli_args)
  File "/Users/benjaminwelch/open-source/coldtype/venv/lib/python3.9/site-packages/coldtype/renderer/reader.py", line 286, in read_configs
    for f in self.config.font_dirs:
AttributeError: 'NoneType' object has no attribute 'font_dirs'
```
I'm probably doing something silly. Any suggestions would be appreciated.

**Comment by stenson** [comment]
good to hear! it's me being silly tho — I actually just pushed a new version (0.5.13) to fix that exact issue which was just introduced yesterday — sorry for the trouble there!

**Comment by benjaminwelch** [comment]
It worked! Thanks so much.

**Comment by matheusmanto** [comment]
Hi! After a while I tried to install again, but I got this error message.
I'm not that good at coding, so I'm sorry if I'm doing something silly.
Thank you!

Running setup.py install for PyOpenGL-accelerate ... error

    ERROR: Command errored out with exit status 1:

     command:
/Users/matheusmantovani/Documents/coldtype/installing-coldtype/venv/bin/python3.9
-u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] =
'"'"'/private/var/folders/1x/1gcltrz51mj4scsdw6b883kw0000gn/T/pip-install-8cgtb8li/pyopengl-accelerate_e72072eda931405d95edda668b01d21a/setup.py'"'"';
__file__='"'"'/private/var/folders/1x/1gcltrz51mj4scsdw6b883kw0000gn/T/pip-install-8cgtb8li/pyopengl-accelerate_e72072eda931405d95edda668b01d21a/setup.py'"'"';f
= getattr(tokenize, '"'"'open'"'"', open)(__file__) if
os.path.exists(__file__) else io.StringIO('"'"'from setuptools import
setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"',
'"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))'
install --record
/private/var/folders/1x/1gcltrz51mj4scsdw6b883kw0000gn/T/pip-record-w8tpnkks/install-record.txt
--single-version-externally-managed --compile --install-headers
/Users/matheusmantovani/Documents/coldtype/installing-coldtype/venv/include/site/python3.9/PyOpenGL-accelerate

         cwd:
/private/var/folders/1x/1gcltrz51mj4scsdw6b883kw0000gn/T/pip-install-8cgtb8li/pyopengl-accelerate_e72072eda931405d95edda668b01d21a/

    Complete output (15 lines):

    Unable to import numpy, skipping numpy extension building

    running install

    running build

    running build_py

    creating build

    creating build/lib.macosx-10.9-x86_64-3.9

    creating build/lib.macosx-10.9-x86_64-3.9/OpenGL_accelerate

    copying OpenGL_accelerate/__init__.py ->
build/lib.macosx-10.9-x86_64-3.9/OpenGL_accelerate

    running build_ext

    building 'OpenGL_accelerate.wrapper' extension

    creating build/temp.macosx-10.9-x86_64-3.9

    creating build/temp.macosx-10.9-x86_64-3.9/src

    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common
-dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch x86_64 -g
-I/private/var/folders/1x/1gcltrz51mj4scsdw6b883kw0000gn/T/pip-install-8cgtb8li/pyopengl-accelerate_e72072eda931405d95edda668b01d21a/..
-I/private/var/folders/1x/1gcltrz51mj4scsdw6b883kw0000gn/T/pip-install-8cgtb8li/pyopengl-accelerate_e72072eda931405d95edda668b01d21a/src
-I/private/var/folders/1x/1gcltrz51mj4scsdw6b883kw0000gn/T/pip-install-8cgtb8li/pyopengl-accelerate_e72072eda931405d95edda668b01d21a
-I/Users/matheusmantovani/Documents/coldtype/installing-coldtype/venv/include
-I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c
src/wrapper.c -o build/temp.macosx-10.9-x86_64-3.9/src/wrapper.o

    xcrun: error: invalid active developer path
(/Library/Developer/CommandLineTools), missing xcrun at:
/Library/Developer/CommandLineTools/usr/bin/xcrun

    error: command '/usr/bin/gcc' failed with exit code 1

    ----------------------------------------

ERROR: Command errored out with exit status 1:
/Users/matheusmantovani/Documents/coldtype/installing-coldtype/venv/bin/python3.9
-u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] =
'"'"'/private/var/folders/1x/1gcltrz51mj4scsdw6b883kw0000gn/T/pip-install-8cgtb8li/pyopengl-accelerate_e72072eda931405d95edda668b01d21a/setup.py'"'"';
__file__='"'"'/private/var/folders/1x/1gcltrz51mj4scsdw6b883kw0000gn/T/pip-install-8cgtb8li/pyopengl-accelerate_e72072eda931405d95edda668b01d21a/setup.py'"'"';f
= getattr(tokenize, '"'"'open'"'"', open)(__file__) if
os.path.exists(__file__) else io.StringIO('"'"'from setuptools import
setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"',
'"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))'
install --record
/private/var/folders/1x/1gcltrz51mj4scsdw6b883kw0000gn/T/pip-record-w8tpnkks/install-record.txt
--single-version-externally-managed --compile --install-headers
/Users/matheusmantovani/Documents/coldtype/installing-coldtype/venv/include/site/python3.9/PyOpenGL-accelerate
Check the logs for full command output.

Em qui., 29 de jul. de 2021 às 18:19, Benjamin Welch <
***@***.***> escreveu:

**Comment by matheusmanto** [comment]
I don't know if it makes any difference, but I recently upgraded to Big Sur
version 11.5.1. Thanks again!

Em sáb., 7 de ago. de 2021 às 09:09, Mantô ***@***.***>
escreveu:

**Comment by matheusmanto** [comment]
IT WORKED! I uploaded my Command Line Tools and it worked - I guess that
was the problem - and, yes, it was silly. Sorry to bother you. And thank
you very much!

PS: I gotta say... Rob Stensons' voice sounds like Seth Rogens' voice,
doesn't it? Thanks again!

Em sáb., 7 de ago. de 2021 às 09:14, Mantô ***@***.***>
escreveu:

**Comment by stenson** [comment]
good to hear! was going to suggest updating the command line tools, glad to hear it wasn't too tough

haha no one's ever told me my voice sounds like seth rogen's!
