### ISSUE TITLE
Making Blender install easier

### ISSUE THREAD

**Issue by colinmford** [coldtype/coldtype#55]
Hey @stenson,

I was wondering if we could brainstorm another way to install coldtype in Blender. 

As I mentioned on twitter, it seems like it's the `unicodedata2` package, looking for `Python.h` when installing via pip. Looking in this project, it's only used in [segmenting.py](https://github.com/goodhertz/coldtype/blob/40d1e4c0ab621368f9f5ed88a6bb89fdd591eda0/coldtype/fontgoggles/misc/segmenting.py) in your `fontgoggles` fork. 

I made a fork where I made `unicodedata2` an optional install, and the rest of coldtype installs easily into Blender's python without having to copy in a bunch of files from the Python source. 

I'm not saying this is for sure the solution, but you can have a look here #54

**Comment by stenson** [comment]
Very nice! Just merged #54 — definitely makes sense to me. It looks like the `noise` package also requires `Python.h`, so I think the move at this point might be to recommend pip installing coldtype into blender without any extras, which is mostly a change to the documentation.

Will update this issue once that work's gotten further / a new version's been released.

Note to future self / thread readers: to fully remove and force recompile of a library like noise or unicodedata2 in the blender python, do a `b3d -m pip uninstall` followed by a `b3d -m pip install <library> --no-cache-dir`

**Comment by stenson** [comment]
Been a while, but just wanted to note here that newer Blenders (> 3) seem not to have the same Python.h issue (in that they include it out-of-the-box), so installing coldtype is much easier now. It's also even easier if you use the new [coldtype-blender](https://github.com/coldtype/coldtype-blender) Blender add-on, as that will do the coldtype installation step for you if you enable the add-on and then hit the "Download & Install Coldtype" button in the add-on itself

**Comment by jishnuthewalker** [comment]
heyy, i think the download and install button in the addon is removed, is there no current was to work coldtype with blender?

**Comment by stenson** [comment]
@jishnuthewalker not sure I've documented it anywhere, but installing coldtype into blender is no longer necessary as coldtype can now inject its dependencies into blender at runtime — the instructions in the README here should work: https://github.com/stenson/coldtype-b3d-examples (if they don't, feel free to start a discussion question on https://github.com/coldtype/coldtype/discussions)
